// src/components/Login.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react';
import Logo from '../assets/logo.png';
import './Logo.css';

const Login = () => {
  return (
    <div className="login-container">
      <div className="login-box">
        <div className="logo-container">
          <img src={Logo} alt="Logo" className="logo" />
        </div>
        <div className="form-container">
          <p className="prompt">Please Login</p>
          <form>
            <div className="input-group">
              <label htmlFor="username">Username</label>
              <input type="text" id="username" name="username" />
            </div>
            <div className="input-group">
              <label htmlFor="password">Single Sign-On Password</label>
              <input type="password" id="password" name="password" />
            </div>
            <button type="submit" className="login-button">Log in</button>
          </form>
          <div className="options">
            <div className="single-sign-on">
              <input type="checkbox" id="single-sign-on" name="single-sign-on" />
              <label htmlFor="single-sign-on">Single Sign-on</label>
            </div>
            <p className="change-password">Change Password</p>
            <p className="reset-password">Reset Password</p>
          </div>
        </div>
        <div className="footer">
          <p>
 generated by or residing upon this System, to the extent permitted by local law, are the property of Citigroup Inc. or one of its subsidiaries or their 
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
