// src/components/Login.jsx
// eslint-disable-next-line no-unused-vars
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Logo from '../../assets/newLogo2.png';
import './Logo.css';

const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleLogin = (e) => {
    e.preventDefault();

    // Fake credentials
    const validUsername = 'admin';
    const validPassword = 'password123';

    if (username === validUsername && password === validPassword) {
      // Navigate to MainPage
      navigate('/main');
    } else {
      alert('Invalid credentials');
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <div className="logo-container">
          <img src={Logo} alt="Logo" className="logo" />
        </div>
        <div className="form-container">
          <p className="prompt">Please Login</p>
          <form className="myForm" onSubmit={handleLogin}>
            <div className="input-group">
              <label htmlFor="username">Username</label>
              <input
                type="text"
                id="username"
                name="username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>
            <div className="input-group">
              <label htmlFor="password">Single Sign-On Password</label>
              <input
                type="password"
                id="password"
                name="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <button type="submit" className="login-button">Log in</button>
          </form>
          <div className="options">
            <div className="single-sign-on">
              <input type="checkbox" id="single-sign-on" name="single-sign-on" />
              <label htmlFor="single-sign-on">Single Sign-on</label>
            </div>
            {/* <p className="change-password">Change Password</p> */}
            <p className="reset-password">Reset Password</p>
          </div>
        </div>
        <div className="footer">
          <p>
            You are authorized to use this System for approved business purposes only. Use for any other purpose is prohibited. All transactional records, reports, email, software, and other data generated by or residing upon this System, to the extent permitted by local law, are the property of Citigroup Inc. Copyright © 2022 Citigroup Inc.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
